/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentID,
  'status' : Status,
  'duration' : bigint,
  'clientId' : ClientID,
  'scheduledTime' : Time,
  'notes' : string,
  'serviceId' : ServiceID,
}
export type AppointmentID = bigint;
export type ClientID = bigint;
export interface PortfolioPhoto {
  'id' : string,
  'serviceTags' : Array<string>,
  'clientId' : ClientID,
  'blob' : string,
  'date' : Time,
  'caption' : string,
  'appointmentId' : [] | [AppointmentID],
}
export interface Product {
  'id' : ProductID,
  'name' : string,
  'unit' : string,
  'minThreshold' : number,
  'supplierNotes' : string,
  'quantity' : number,
  'category' : string,
  'brand' : string,
}
export type ProductID = bigint;
export interface Service {
  'id' : ServiceID,
  'duration' : bigint,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'price' : number,
}
export type ServiceID = bigint;
export type Status = { 'finished' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'isExpense' : boolean,
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'amount' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<[string, string, string, string], ClientID>,
  'addProduct' : ActorMethod<
    [string, string, string, string, number, number, string],
    ProductID
  >,
  'addService' : ActorMethod<[string, string, bigint, number], ServiceID>,
  'addTransaction' : ActorMethod<[number, string, boolean, string], bigint>,
  'addVisitToClient' : ActorMethod<[ClientID, AppointmentID], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<
    [ClientID, ServiceID, Time, bigint, string],
    AppointmentID
  >,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAppointmentsByStatus' : ActorMethod<[Status], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getMonthlyAggregates' : ActorMethod<
    [bigint],
    Array<[string, number, number]>
  >,
  'getPortfolioPhotosByServiceTag' : ActorMethod<
    [string],
    Array<PortfolioPhoto>
  >,
  'getProduct' : ActorMethod<[ProductID], [] | [Product]>,
  'getService' : ActorMethod<[ServiceID], [] | [Service]>,
  'getTodayAppointments' : ActorMethod<[], Array<Appointment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setServiceStatus' : ActorMethod<[ServiceID, boolean], undefined>,
  'updateLoyaltyPoints' : ActorMethod<[ClientID, bigint], undefined>,
  'updateProductQuantity' : ActorMethod<[ProductID, number], undefined>,
  'updateTransaction' : ActorMethod<
    [bigint, number, string, boolean, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];