/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ClientID = IDL.Nat;
export const ProductID = IDL.Nat;
export const ServiceID = IDL.Nat;
export const AppointmentID = IDL.Nat;
export const Time = IDL.Int;
export const Client = IDL.Record({
  'id' : ClientID,
  'contactInfo' : IDL.Text,
  'visitHistory' : IDL.Vec(AppointmentID),
  'name' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'preferences' : IDL.Text,
  'allergies' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductID,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'minThreshold' : IDL.Float64,
  'supplierNotes' : IDL.Text,
  'quantity' : IDL.Float64,
  'category' : IDL.Text,
  'brand' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : ServiceID,
  'duration' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const Status = IDL.Variant({
  'finished' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : AppointmentID,
  'status' : Status,
  'duration' : IDL.Nat,
  'clientId' : ClientID,
  'scheduledTime' : Time,
  'notes' : IDL.Text,
  'serviceId' : ServiceID,
});
export const PortfolioPhoto = IDL.Record({
  'id' : IDL.Text,
  'serviceTags' : IDL.Vec(IDL.Text),
  'clientId' : ClientID,
  'blob' : IDL.Text,
  'date' : Time,
  'caption' : IDL.Text,
  'appointmentId' : IDL.Opt(AppointmentID),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ClientID],
      [],
    ),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [ProductID],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [ServiceID],
      [],
    ),
  'addVisitToClient' : IDL.Func([ClientID, AppointmentID], [], []),
  'createAppointment' : IDL.Func(
      [ClientID, ServiceID, Time, IDL.Nat, IDL.Text],
      [AppointmentID],
      [],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAppointmentsByStatus' : IDL.Func(
      [Status],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getPortfolioPhotosByServiceTag' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioPhoto)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductID], [IDL.Opt(Product)], ['query']),
  'getService' : IDL.Func([ServiceID], [IDL.Opt(Service)], ['query']),
  'getTodayAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'setServiceStatus' : IDL.Func([ServiceID, IDL.Bool], [], []),
  'updateLoyaltyPoints' : IDL.Func([ClientID, IDL.Nat], [], []),
  'updateProductQuantity' : IDL.Func([ProductID, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ClientID = IDL.Nat;
  const ProductID = IDL.Nat;
  const ServiceID = IDL.Nat;
  const AppointmentID = IDL.Nat;
  const Time = IDL.Int;
  const Client = IDL.Record({
    'id' : ClientID,
    'contactInfo' : IDL.Text,
    'visitHistory' : IDL.Vec(AppointmentID),
    'name' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'preferences' : IDL.Text,
    'allergies' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductID,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'minThreshold' : IDL.Float64,
    'supplierNotes' : IDL.Text,
    'quantity' : IDL.Float64,
    'category' : IDL.Text,
    'brand' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : ServiceID,
    'duration' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Status = IDL.Variant({
    'finished' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : AppointmentID,
    'status' : Status,
    'duration' : IDL.Nat,
    'clientId' : ClientID,
    'scheduledTime' : Time,
    'notes' : IDL.Text,
    'serviceId' : ServiceID,
  });
  const PortfolioPhoto = IDL.Record({
    'id' : IDL.Text,
    'serviceTags' : IDL.Vec(IDL.Text),
    'clientId' : ClientID,
    'blob' : IDL.Text,
    'date' : Time,
    'caption' : IDL.Text,
    'appointmentId' : IDL.Opt(AppointmentID),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ClientID],
        [],
      ),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [ProductID],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [ServiceID],
        [],
      ),
    'addVisitToClient' : IDL.Func([ClientID, AppointmentID], [], []),
    'createAppointment' : IDL.Func(
        [ClientID, ServiceID, Time, IDL.Nat, IDL.Text],
        [AppointmentID],
        [],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAppointmentsByStatus' : IDL.Func(
        [Status],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getPortfolioPhotosByServiceTag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioPhoto)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductID], [IDL.Opt(Product)], ['query']),
    'getService' : IDL.Func([ServiceID], [IDL.Opt(Service)], ['query']),
    'getTodayAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'setServiceStatus' : IDL.Func([ServiceID, IDL.Bool], [], []),
    'updateLoyaltyPoints' : IDL.Func([ClientID, IDL.Nat], [], []),
    'updateProductQuantity' : IDL.Func([ProductID, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };