/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ClientID = IDL.Nat;
export const ProductID = IDL.Nat;
export const ServiceID = IDL.Nat;
export const AppointmentID = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductID,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'minThreshold' : IDL.Float64,
  'supplierNotes' : IDL.Text,
  'quantity' : IDL.Float64,
  'category' : IDL.Text,
  'brand' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : ServiceID,
  'duration' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'isExpense' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Status = IDL.Variant({
  'finished' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : AppointmentID,
  'status' : Status,
  'duration' : IDL.Nat,
  'clientId' : ClientID,
  'scheduledTime' : Time,
  'notes' : IDL.Text,
  'serviceId' : ServiceID,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PortfolioPhoto = IDL.Record({
  'id' : IDL.Text,
  'serviceTags' : IDL.Vec(IDL.Text),
  'clientId' : ClientID,
  'blob' : IDL.Text,
  'date' : Time,
  'caption' : IDL.Text,
  'appointmentId' : IDL.Opt(AppointmentID),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ClientID],
      [],
    ),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [ProductID],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [ServiceID],
      [],
    ),
  'addTransaction' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Bool, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addVisitToClient' : IDL.Func([ClientID, AppointmentID], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func(
      [ClientID, ServiceID, Time, IDL.Nat, IDL.Text],
      [AppointmentID],
      [],
    ),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAppointmentsByStatus' : IDL.Func(
      [Status],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMonthlyAggregates' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64))],
      ['query'],
    ),
  'getPortfolioPhotosByServiceTag' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioPhoto)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductID], [IDL.Opt(Product)], ['query']),
  'getService' : IDL.Func([ServiceID], [IDL.Opt(Service)], ['query']),
  'getTodayAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setServiceStatus' : IDL.Func([ServiceID, IDL.Bool], [], []),
  'updateLoyaltyPoints' : IDL.Func([ClientID, IDL.Nat], [], []),
  'updateProductQuantity' : IDL.Func([ProductID, IDL.Float64], [], []),
  'updateTransaction' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'verifyAdminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ClientID = IDL.Nat;
  const ProductID = IDL.Nat;
  const ServiceID = IDL.Nat;
  const AppointmentID = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductID,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'minThreshold' : IDL.Float64,
    'supplierNotes' : IDL.Text,
    'quantity' : IDL.Float64,
    'category' : IDL.Text,
    'brand' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : ServiceID,
    'duration' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'isExpense' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Status = IDL.Variant({
    'finished' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : AppointmentID,
    'status' : Status,
    'duration' : IDL.Nat,
    'clientId' : ClientID,
    'scheduledTime' : Time,
    'notes' : IDL.Text,
    'serviceId' : ServiceID,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PortfolioPhoto = IDL.Record({
    'id' : IDL.Text,
    'serviceTags' : IDL.Vec(IDL.Text),
    'clientId' : ClientID,
    'blob' : IDL.Text,
    'date' : Time,
    'caption' : IDL.Text,
    'appointmentId' : IDL.Opt(AppointmentID),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ClientID],
        [],
      ),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [ProductID],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [ServiceID],
        [],
      ),
    'addTransaction' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Bool, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addVisitToClient' : IDL.Func([ClientID, AppointmentID], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func(
        [ClientID, ServiceID, Time, IDL.Nat, IDL.Text],
        [AppointmentID],
        [],
      ),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAppointmentsByStatus' : IDL.Func(
        [Status],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMonthlyAggregates' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64))],
        ['query'],
      ),
    'getPortfolioPhotosByServiceTag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioPhoto)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductID], [IDL.Opt(Product)], ['query']),
    'getService' : IDL.Func([ServiceID], [IDL.Opt(Service)], ['query']),
    'getTodayAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setServiceStatus' : IDL.Func([ServiceID, IDL.Bool], [], []),
    'updateLoyaltyPoints' : IDL.Func([ClientID, IDL.Nat], [], []),
    'updateProductQuantity' : IDL.Func([ProductID, IDL.Float64], [], []),
    'updateTransaction' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'verifyAdminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };